#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see https://aka.ms/containercompat

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
COPY . .

RUN dotnet restore Polls.Api/Polls.Api.csproj

FROM build AS publish
RUN dotnet publish Polls.Api/Polls.Api.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .

RUN dotnet dev-certs https -ep %USERPROFILE%\.aspnet\https\aspnetapp.pfx -p 5tgbNHY^
RUN dotnet dev-certs https --trust

ENTRYPOINT ["dotnet", "Polls.Api.dll"]
