version: '3.4'

services:
  polls-gui:
    ports:
      - "3000:80"
  polls-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__PollsDb=Server=sql-server;Database=PollsDb;User=sa;Password=5tgbNHY^;
      - InMemoryDatabase=false
      - JwtConfig__Key=JwtTokenClientSettings123456
      - JwtConfig__expiresIn=99999
      - RabbitMqSettings__RabbitMqConnectionSettings__Hostname=rabbitmq
    ports:
      - "5003:80"
  sql-server:
    ports:
      - "1433:1433"
