version: '3.4'

services:
  polls-gui:
    environment:
      - API_BASE_URL=http://54.89.158.217:5000
      - WEB_PUSH_PUBLIC_KEY=BJ5IxJBWdeqFDJTvrZ4wNRu7UY2XigDXjgiUBYEYVXDudxhEs0ReOJRBcBHsPYgZ5dyV8VjyqzbQKS8V7bUAglk
      - NOTIFICATIONS_API_URL=http://54.89.158.217:4000
    ports:
      - "3000:3000"
  polls-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__PollsDb=Server=sql-server;Database=PollsDb;User=sa;Password=5tgbNHY^;
      - InMemoryDatabase=false
      - JwtConfig__Key=JwtTokenClientSettings123456
      - JwtConfig__expiresIn=99999
      - RabbitMqSettings__Hostname=rabbitmq
    ports:
      - "5000:80"
  push-notifications-api:
    environment:
      - PORT=4000
      - WEB_PUSH_PUBLIC_KEY=BJ5IxJBWdeqFDJTvrZ4wNRu7UY2XigDXjgiUBYEYVXDudxhEs0ReOJRBcBHsPYgZ5dyV8VjyqzbQKS8V7bUAglk
      - WEB_PUSH_PRIVATE_KEY=ERIZmc5T5uWGeRxedxu92k3HnpVwy_RCnQfgek1x2Y4
      - MS_SQL_SERVER=sql-server
      - MS_SQL_USERNAME=sa
      - MS_SQL_PASSWORD=5tgbNHY^
      - MS_SQL_DB=PollsDb
      - RABBIT_MQ_SERVER_URL=rabbitmq
      - NUMBER_OF_SUBSCRIPTIONS_PER_BROADCAST=100
    ports:
      - "4000:4000"
